//创建一个新用户
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const FETCH_CREATE_NEW_USER_START = "FETCH_CREATE_NEW_USER_START";
export const FETCH_CREATE_NEW_USER_SUCCESS = "FETCH_CREATE_NEW_USER_SUCCESS";
export const FETCH_CREATE_NEW_USER_FAILED = "FETCH_CREATE_NEW_USER_FAILED";

//登出
export const LOGIN_OUT = "LOGIN_OUT";

//用户改密码
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const FETCH_CHANGE_PASSWORD_START = "FETCH_CHANGE_PASSWORD_START";
export const FETCH_CHANGE_PASSWORD_SUCCESS = "FETCH_CHANGE_PASSWORD_SUCCESS";
export const FETCH_CHANGE_PASSWORD_FAILED = "FETCH_CHANGE_PASSWORD_FAILED";

//获取帖子列表
export const FETCH_FEED_LIST_START = "FETCH_FEED_LIST_START";
export const FETCH_FEED_LIST_SUCCESS = "FETCH_FEED_LIST_SUCCESS";
export const FETCH_FEED_LIST_FAILED = "FETCH_FEED_LIST_FAILED";

//获取单个帖子
export const FETCH_SINGLE_POST_SUCCESS = "FETCH_SINGLE_POST_SUCCESS";

//验证登录
export const FETCH_LOGIN_IN_START = "FETCH_LOGIN_IN_START";
export const FETCH_LOGIN_IN_SUCCESS = "FETCH_LOGIN_IN_SUCCESS";
export const FETCH_LOGIN_IN_FAILED = "FETCH_LOGIN_IN_FAILED";


//改变帖子页码
export const CHANGE_POST_PAGE = "CHANGE_POST_PAGE";

//获取帖子的总数
export const FETCH_FEED_LIST_LEN_SUCCESS = "FETCH_FEED_LIST_LEN_SUCCESS";

//获取帖子

export const FETCH_DISCUSSION_FAILED = "FETCH_DISCUSSION_FAILED";
export const FETCH_DISCUSSION_SUCCESS = "FETCH_DISCUSSION_SUCCESS";

export const GET_POSTID = "GET_POSTID";
export const GET_POST_MESSAGE = "GET_POST_MESSAGE";
export const CHANGE_REPLY_PAGE = "CHANGE_REPLY_PAGE";

export const FETCH_CREATE_REPLY_SUCCESS = "FETCH_CREATE_REPLY_SUCCESS";

export const FETCH_DELETE_REPLY_SUCCESS = "FETCH_DELETE_REPLY_SUCCESS";